services:
  ehr_internal_postgres:
    image: postgres:18.1
    container_name: ehr_internal_postgres
    environment:
      POSTGRES_USER: ehr_admin
      POSTGRES_PASSWORD: ehr_admin_pw
      POSTGRES_DB: ehr_internal
    ports:
      - "5433:5432"
    volumes:
      - ehr_internal_data:/var/lib/postgresql/data
      - ./dynamic_exports/ehr/init.sql:/docker-entrypoint-initdb.d/init.sql

  ehr_mirror_postgres:
    image: postgres:18.1
    container_name: ehr_mirror_postgres
    environment:
      POSTGRES_USER: mirror_admin
      POSTGRES_PASSWORD: mirror_admin_pw
      POSTGRES_DB: ehr_mirror
    ports:
      - "5434:5432"
    volumes:
      - ehr_mirror_data:/var/lib/postgresql/data
  urgent_care_postgres:
    image: postgres:15
    container_name: urgent_care_postgres
    environment:
      POSTGRES_USER: uc_user
      POSTGRES_PASSWORD: uc_password
      POSTGRES_DB: uc
    ports:
      - "5434:5432"
    volumes:
      - ./dynamic_exports/urgent_care/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
