postgres:
  ehr_internal_dsn: postgresql+psycopg2://trust_admin:t_lnl.%5EC-MA3jXJhyuBUs-a4.8aHSr@localhost:5433/ehr
  urgent_internal_dsn: postgresql+psycopg2://trust_admin:t_lnl.%5EC-MA3jXJhyuBUs-a4.8aHSr@localhost:5433/urgent_care
  ehr_mirror_dsn: postgresql+psycopg2://trust_admin:t_lnl.%5EC-MA3jXJhyuBUs-a4.8aHSr@localhost:5433/ehr_mirror
  urgent_mirror_dsn: postgresql+psycopg2://trust_admin:t_lnl.%5EC-MA3jXJhyuBUs-a4.8aHSr@localhost:5433/urgent_care_mirror
sftp:
  host: s-df0e67cf50c74e36a.server.transfer.eu-west-2.amazonaws.com
  port: 22
  username: trust_sftp
  password: fU9WekNOnB9aDiKTux6qVbwf3A1cc5k3
  outbound_root: /outbound
s3:
  region: eu-west-2
  profile: northshire-trust
  assume_role_arn: arn:aws:iam::911848242214:role/NorthshireS3Publisher
  assume_role_session_name: northshire-hospital-sim
  endpoint_url: null
  use_sse_s3: true
  kms_key_id: null
  bucket: northshire-trust-exports-911848242214
  prefixes:
    diagnostics: diagnostics
    providers: providers
