postgres:
  ehr_internal_dsn: postgresql+psycopg2://trust_admin:U_jrNjSHiyTuiI%2C0t2Bw4n.MrPLydP@localhost:5433/ehr
  urgent_internal_dsn: postgresql+psycopg2://trust_admin:U_jrNjSHiyTuiI%2C0t2Bw4n.MrPLydP@localhost:5433/urgent_care
  ehr_mirror_dsn: postgresql+psycopg2://trust_admin:U_jrNjSHiyTuiI%2C0t2Bw4n.MrPLydP@localhost:5433/ehr_mirror
  urgent_mirror_dsn: postgresql+psycopg2://trust_admin:U_jrNjSHiyTuiI%2C0t2Bw4n.MrPLydP@localhost:5433/urgent_care_mirror
sftp:
  host: s-bc5c2c212e914725b.server.transfer.eu-west-2.amazonaws.com
  port: 22
  username: trust_sftp
  password: FG6RCJQS5rUs6zYaM7qFf0WHjtZ6aZbK
  outbound_root: /outbound
s3:
  region: eu-west-2
  profile: northshire-trust
  assume_role_arn: arn:aws:iam::911848242214:role/NorthshireS3Publisher
  assume_role_session_name: northshire-hospital-sim
  endpoint_url: null
  use_sse_s3: true
  kms_key_id: null
  bucket: northshire-trust-exports-911848242214
  prefixes:
    diagnostics: diagnostics
    providers: providers
